### ISSUE TITLE
Readme.md still not informative, add more knowledgeable

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/react-coming-soon-template#1]
Add prerequisite on readme.md and minimum requirement.

**Comment by mySuulola** [comment]
What exactly is the prerequisite and what is the minimum requirement of the project

**Comment by arrlancore** [comment]
> What exactly is the prerequisite and what is the minimum requirement of the project

You can refer to this good example: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by ThomasNolte** [comment]
I've created a PR #20 for this issue let me know if it is what your looking for.

@arrlancore
