### ISSUE TITLE
Add social media icon

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/react-coming-soon-template#12]
Need to add social media icon on the below of button, it might be linkedin, instagram, facebook and twitter. Icon can be from material icon, simpleicons.org, etc. Please use white color for the icon.

**Comment by Shadmanwaris** [comment]
Can I take this ?

**Comment by arrlancore** [comment]
> Can I take this ?

Yes sure, thanks

**Comment by vvit5827** [comment]
I've done that in #22
