### ISSUE TITLE
Add new props "time" for countdown timer component

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/react-coming-soon-template#15]
Currently, we already have a countdown timer component, but it still use date for the parameter. It will be good if we can also add specific time for the countdown time.

Current props: 
`date="10/30/2018"`
Expected:
`date="10/30/2018"`
`time="18.00"`

**Comment by juancjara** [comment]
I'll take it, btw the time format should it be like this "18:00" with `colon` instead of `period` ?

**Comment by juancjara** [comment]
closes #17
