### ISSUE TITLE
Add feature auto sliding image for the background

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/react-coming-soon-template#16]
Now its only have a static background for the main page coming soon. It will be great if we can add multiple image background with autoplay slides. and free to use any slides image library such us react slick, etc.

**Comment by ulziibuyan** [comment]
I'd like to work on it.

**Comment by arrlancore** [comment]
> I'd like to work on it.

You are welcome

**Comment by ulziibuyan** [comment]
Sorry for blocking. I gave up.

**Comment by clariokids** [comment]
check my PR @arrlancore
