### ISSUE TITLE
Countdown timer feature

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/react-coming-soon-template#3]
Add countdown time, so the visitor will know when the website will launch

**Comment by Qo2770** [comment]
I could implement such a timer. Should it be on the index..js file?

**Comment by arrlancore** [comment]
> I could implement such a timer. Should it be on the index..js file?

Yes, it would be placed on the index.js.

**Comment by eeshdarthvader** [comment]
I have added Timer component. Please review.

https://github.com/arrlancore/react-coming-soon-template/pull/10
