### ISSUE TITLE
Use react particleJs

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/react-coming-soon-template#31]
Lets make the cool background with react particleJs.

**Comment by nmenal** [comment]
can i ?

**Comment by jgilbertcastro** [comment]
doing

**Comment by jgilbertcastro** [comment]
> Lets make the cool background with react particleJs.

done

**Comment by arrlancore** [comment]
#32 Thanks all

**Comment by arrlancore** [comment]
> can i ?

Thanks for your interesting. Basically you can take it where the issue is still open, maybe we will have new feature to be added soon.
