### ISSUE TITLE
Connect form to mailchimp

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/react-coming-soon-template#4]
Connect email form to mailchimp, so all data save on the mailing list of mailchimp

**Comment by prakash9494** [comment]
can u please create a free account in mailchip.com so that any one can work on this issue

**Comment by arrlancore** [comment]
> can u please create a free account in mailchip.com so that any one can work on this issue

Thank you @prakash9494  for your suggestion, instead. Please use your own account and just remove the API Key once you want to push to GitHub.
